lives = 3
bricks = []
brick_len = 5
start_time = 0
score = 0
fall_powerup = []
active_powerup = []
paddle_attach = True
no_len_plus = 0
no_len_minus = 0
no_bricks = 0
overlap = 0
overlap_one = 0
overlap_4 = 0
second_way = 0
through_ball = False
brick_fall=False
brick_fall_time = 100
brick_fall_paddle_touch = True
paddle_shooter = False
bullet = []
bullet_iter=0
bullet_time = 0
level = 0
boss_length = 32
bombs = []
boss_health = 10
life_end = False